import { Footer } from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import { TopBar } from "@/components/layout/Topbar";
import { FOOTER_CONFIG, TOPBAR_CONFIG } from "@/constants";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="from-muted to-muted/40 min-h-screen bg-gradient-to-b ">
      <TopBar {...TOPBAR_CONFIG} />
      <div className="sticky inset-x-0 top-0 z-[30]">
        <Header />
      </div>
      <div className="p-0 m-0">{children}</div>
      <Footer {...FOOTER_CONFIG} />
    </div>
  );
}
